### ISSUE TITLE
Phonetic alphabet revisions

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#258]
@pcraig3 

Please replace the current word for the letter E with  (English) Espresso  and (French) Espresso

Please replace the current word for the letter I with  (English)  Identity and (French)  Identité

Please capitalize all words in the phonetic alphabet.

Merci beaucoup!!

**Comment by pcraig3** [comment]
Updated the current word for "E" from "Elephant" to "Espresso".

We don't have I's coming back because they look too similar to "1" and "l", so for that one we don't have to make any changes to our app.

**Comment by pcraig3** [comment]
This is closed since #257
