### ISSUE TITLE
Change to FR votre compte page

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#265]
@pcraig3 I know that the yubikey part is just for CDS staff, but for our Francophone staff 
Ps change "clef Yubikey" in staging to "clé Yubikey"
on https://staging.covid-hcportal.cdssandbox.xyz/fr/profiles/3c0d242c-8231-4c96-a48e-f5e3e74166be

Merci!

**Comment by anikbrazeau** [comment]
Change looks good!
