### ISSUE TITLE
Confirm invitation removal in French 

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#267]
@pcraig3 
in this page, the French heading is in English 
https://staging.covid-hcportal.cdssandbox.xyz/en/invite/1183/delete

Instead of adding the French translation, I would like to delete the English heading as well, and make the first sentence the heading in both languages.
So the headings would be 

Are you sure you want to delete the invitation sent to yedida.zalik+123@cds-snc.ca?

Êtes-vous certain de vouloir retirer l‘invitation envoyée à yedida.zalik+123@cds-snc.ca?

Is this possible with the email address in the heading ?  If not, I'll address this another way.

**Comment by anikbrazeau** [comment]
Change looks good!
