### ISSUE TITLE
French phonetic alphabet phrase 

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#268]
@pcraig3 
In the blue box, can you please add "dans" after each instance of "comme" (the way it is in figma) on both the Generated key and Instructions pages?

example:  A comme dans Animal

Merci!

**Comment by pcraig3** [comment]
Hi Yedida, I think this one is already done. This is what it looks like right now on staging:

![image](https://user-images.githubusercontent.com/2454380/95260905-808d6a00-07f7-11eb-879d-bd5085ebb4be.png)

**Comment by YedidaZalik** [comment]
apologies @pcraig3  must have got wires crossed!
