### ISSUE TITLE
Nous joindre needs French error messages

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#274]
Oops @pcraig3 apologies, I missed this French one

The error message are in English on this page 
https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=3300%3A18078

For missing email, please change to 

Saisissez votre adresse courriel si vous souhaitez nous joindre

For missing comment box, please change to 

Écrivez quelque chose si vous souhaitez nous joindre :

Merci beaucoup!

**Comment by pcraig3** [comment]
Hi Yedida, these are both on staging right now: 

![image](https://user-images.githubusercontent.com/2454380/95619161-2d582900-0a3c-11eb-807e-5f30d728dfc3.png)

What you're probably seeing is the in-browser validation that we have — that's not controlled by is, it's Chrome or FF or whatever that puts that message there. We can remove all our in-browser validation but nobody has really asked us to yet.

![image](https://user-images.githubusercontent.com/2454380/95619274-57a9e680-0a3c-11eb-8f30-c42ee27d8a1b.png)

**Comment by YedidaZalik** [comment]
@pcraig3 I tried again, but still when I submit something using the "Nous joindre" page from staging in French, those red messages don't show up. I just get "Please fill out this field" in English.
