### ISSUE TITLE
Contact us page leads to error message

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#275]
@pcraig3 When trying to submit something on the contact us page on staging, both Anik & I got an error message
that said "There was a problem and your feedback wasn’t submitted. Please email your feedback to assistance+healthcare@cds-snc.ca."

This happened in both English and French

https://staging.covid-hcportal.cdssandbox.xyz/en/contact/

**Comment by sidewalkballet** [comment]
This is expected; staging is not linked to freshdesk, only prod.
