### ISSUE TITLE
Your account  - timing of password change

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#278]
@pcraig3  in figma on this page, we indicate when the password was last changed (Last changed 22 hours ago)

Is that also possible in staging?

**Comment by pcraig3** [comment]
Hi @YedidaZalik, we talked about this the other day and I thought we agreed to forego this. I'm not sure if we actually have the "last changed" information in our DB, and if someone's password is changed without them knowing (probably the intent of this message), then they probably can't log in anymore. 

I think we should update the Figma mocks to just not have anything in there. @brianhendrick1, what do you think?

**Comment by YedidaZalik** [comment]
oh, okay that's fine with me, @pcraig3 @brianhendrick1 
I'm removing it from figma and closing this issue.
