### ISSUE TITLE
Covid alert app raises alert on and off

### ISSUE THREAD

**Issue by sri3bala** [cds-snc/covid-alert-portal#294]
Hi,

I installed the app on the first day when it became available. 

Suddenly, app raised the alert saying that I have been exposed to covid positive person in the last 14 days. It did not give any indication as to when and where. 

I think it is pretty useless if it could not tell at least the date when the alert came on. 

One normal person asked, why id it waiting 15 minutes and then raised the alert instead of raising the alert (similar to emergency text that we get) as soon as it detects that say within a minute?  Pretty basic right ?

I got nervous and I am a heart patient. I told the employer and got home and then went to test. It was another hectic story. Anyway, test result came after  days, that was another nightmare. it was negative. There is no way to enter the key in the app.

App alert went off after few days, then after few days, the alert came back on. I have no idea what is going on. At this point, as you can imagine, I lost my confidence with it. It is pretty useless app.

Why don't you fix these issues and release new updates ? I have not seen any update for the app from the beginning.

How would one person who was positive and then later negative enter the key in his/her app so it does not tell other phones nearby false notifications ?

Why don't you do good test ?  If this app was pretty solid, it would have prevented the latest raise in infections.  

Thanks,
Sri Bala

**Comment by pcraig3** [comment]
Hi Sri,

Thanks for the message. I forwarded it to my colleagues and they mentioned that they saw this message come in through a  security email and have responded to it there. 

Sorry for the bad experience you have had, but we take all feedback seriously and it helps us improve the app for others. Thank you for reaching out! 

Paul
