### ISSUE TITLE
Changes to "Change your password" flow

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#340]
@pcraig3 

Please change as follows in both English and French
All the hint text is on the screen, but there should be just one line: “Your password must be at least 12 characters and hard to guess.” 
The other hint text is only meant to show if the user makes that particular error.

Please replace 
"Confirm your password
Enter the same password as above."
 with “Enter your password again”   and in French with "Saisissez de nouveau votre mot de passe"

**Comment by pcraig3** [comment]
> Please change as follows in both English and French
> All the hint text is on the screen, but there should be just one line: “Your password must be at least 12 characters and hard to guess.”
> The other hint text is only meant to show if the user makes that particular error.

Best practice is that the user would have all the information they need at the time they are performing the action. In this case, we have 4 ways to disallow a password (length, similarity, all numbers, not complex), so we don't want to surprise people with restrictions if they have already typed in a password. 

We can change the words or the formatting (eg, doesn't have to be 4 separate sentences), but I think it's important to keep the relevant information around.

**Comment by YedidaZalik** [comment]
Okay, then please move the hint text to replace the content in the form field label.
I've drafted new password content and I'll give that to you once it's been translated.
Thanks @pcraig3

**Comment by YedidaZalik** [comment]
@pcraig3 
Here is the new password content in both languages:

Choose a password that is hard to guess, with at least 12 characters including 1 letter.
The password cannot include your name, email or words related to Covid or the portal.

Choisissez un mot de passe difficile à deviner et comprenant au moins 12 caractères, dont au moins une lettre.
Le mot de passe ne peut pas comprendre votre nom, votre courriel ou des mots faisant référence à la COVID ou au portail.
