### ISSUE TITLE
Changes to "Team management" flow

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#341]
@pcraig3 

**Manage team screen** (aka Manage accounts)

Please change “Edit” to “Manage” 
Please also make the change in French as shown in mockups here: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=4361%3A652

**Security code screen** (aka Offline 2FA admin for staff)

Please change “Staff member”to  “team member”  - (English change only)

Please change button to “Back to Manage team””  and also in French as shown here: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=4715%3A12

**Comment by pcraig3** [comment]
Closing this: code was merged yesterday and reviewed today.
