### ISSUE TITLE
Changes to "Generating OTK" flow

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#342]
@pcraig3 

Please change some words in banner for “You have 1 security code left” 

Please change “Remaining” to “left”

Please change “Your account” to “Manage your account” and in French please change to follow this mock-up:https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=4800%3A27659

**Comment by pcraig3** [comment]
Pretty sure changes are all done for this, reviewed by @YedidaZalik and I made the change to the top menu in #346
