### ISSUE TITLE
Content change to security codes screen

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#353]
@pcraig3 

To emphasize that HCWs should save their codes, please make the following replacement in English and French:

Please replace "Keep the codes somewhere that only you can access. "

with 

English :  "**Before you do anything else, save these codes somewhere that only you can access.**" 

French:  "**Avant toute autre chose, enregistrez ces codes dans un endroit auquel vous seul pouvez accéder.**"

**Comment by pcraig3** [comment]
This issue was resolved in #354
