### ISSUE TITLE
Content change to account invite expiry screen

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#356]
@pcraig3 please change this screen to match the pink replacement screens in figma

For English: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=6375%3A38691

For French:  https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=6385%3A2

I'll change the pink figma to black when you're done.  

Merci beaucoup!

**Comment by pcraig3** [comment]
closed since #358
