### ISSUE TITLE
Update content for https://covid-alert-temp-just-n-fqbd7o.herokuapp.com/en/location/category/

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#392]
@dsamojlenko 

Please use figma content from https://www.figma.com/file/0CvVmmVb0EhnCmChzel70P/QR-Code-Registration-Website?node-id=179%3A834

French translation coming later.

Merci!

**Comment by sakura-sketch** [comment]
Made the changes based on the figma poster

![image](https://user-images.githubusercontent.com/72329480/109535871-0d78de80-7a8b-11eb-91d1-8654acbd3885.png)
