### ISSUE TITLE
Create translation keys

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/covid-alert-portal#405]
Some translation keys are missing. Here are the details and screenshots for each:

- The form field "Full name" doesn't seem to have a translation key in register/templates.
- The word "Change" in the 'Check your answers page' doesn't have a translation key.
- The word "Or" and the linked text for "contact us", on the onboarding page, don't have translation keys. (A translation key for another "Contact us" phrase already exists but we should have another one here.)
- The form field "Contact email" doesn't seem to have a translation key in register/templates (I saw one in outbreaks/templates with a (wrong) translation, but it's not showing up on the registration website).

![Capture d’écran, le 2021-03-03 à 14 28 52](https://user-images.githubusercontent.com/45772213/109866375-32a85100-7c33-11eb-9a37-65fd8f1268ea.png)

![Capture d’écran, le 2021-03-03 à 14 40 56](https://user-images.githubusercontent.com/45772213/109865082-a47f9b00-7c31-11eb-9838-84695c5ee34d.png)

![Capture d’écran, le 2021-03-03 à 14 47 20](https://user-images.githubusercontent.com/45772213/109865778-7a7aa880-7c32-11eb-8e64-1d2010cb6658.png)

![Capture d’écran, le 2021-03-03 à 14 39 02](https://user-images.githubusercontent.com/45772213/109866302-1dcbbd80-7c33-11eb-8b3e-72291b89f245.png)

**Comment by sakura-sketch** [comment]
The changes for this issue were merged
