### ISSUE TITLE
Divide a link into plain text + link

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/covid-alert-portal#407]
On the onboarding page, we should only link "Help with your poster" (in French: "Aide pour votre affiche"). 

reference in Figma: https://www.figma.com/file/0CvVmmVb0EhnCmChzel70P/QR-Code-Registration-Website?node-id=1138%3A2

Currently all the text is linked: 
![Capture d’écran, le 2021-03-03 à 15 22 38](https://user-images.githubusercontent.com/45772213/109867969-1d342680-7c35-11eb-94b0-d37a9bf38df4.png)

**Comment by sakura-sketch** [comment]
The changes for this issue were merged
