### ISSUE TITLE
Update type of place or event options

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#587]
On Type of place or event (step 1), Figma shows radio buttons rather than dropdown?

Options themselves are also inconsistent with Figma:
- `Events such as festivals, weddings, conferences` should be `Events and private functions such as festivals, weddings, conferences`

- `Medical office or centre (doctor, dentist, etc.)` should be `Medical centres such as doctor or dentist offices`

![Screen Shot 2021-06-08 at 10 50 25 PM](https://user-images.githubusercontent.com/38330843/121285347-3e4b8980-c8ac-11eb-901c-0569c5b447ae.png)

_Difference observed when comparing QR code registration [staging site](https://register.covid-hcportal.cdssandbox.xyz/en/) and [Figma](https://www.figma.com/file/0CvVmmVb0EhnCmChzel70P/QR-Code-Registration-Website?node-id=3614%3A19354)_

**Comment by anikbrazeau** [comment]
@YedidaZalik can confirm what are the correct/latest options?

**Comment by YedidaZalik** [comment]
Staging is correct !
