### ISSUE TITLE
Add 'Next' button arrow

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#589]
<img width="354" alt="Screen Shot 2021-06-08 at 10 55 57 PM" src="https://user-images.githubusercontent.com/38330843/121285673-c5006680-c8ac-11eb-8886-9d3211a992e2.png">

_Difference observed when comparing QR code registration [staging site](https://register.covid-hcportal.cdssandbox.xyz/en/) and [Figma](https://www.figma.com/file/0CvVmmVb0EhnCmChzel70P/QR-Code-Registration-Website?node-id=3614%3A19354)_

**Comment by anikbrazeau** [comment]
@ioanacontu should there be arrows on staging?

**Comment by ioanacontu** [comment]
No arrows for "Next" buttons. Thank you! 

The only buttons that have arrows are the green ones: 
<img width="403" alt="Screen Shot 2021-06-14 at 10 56 40" src="https://user-images.githubusercontent.com/56094538/121913382-5afa1e00-ccff-11eb-8526-2558d53d274b.png">
<img width="324" alt="Screen Shot 2021-06-14 at 10 56 52" src="https://user-images.githubusercontent.com/56094538/121913385-5afa1e00-ccff-11eb-9704-5bf5ef9be334.png">

**Comment by anikbrazeau** [comment]
Closing this issue as it is no longer relevant
