### ISSUE TITLE
Make it possible to go back or return home for "Invalid" error

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#590]
Currently there is no way back or out if link is expired. 

![Screen Shot 2021-06-08 at 10 58 44 PM](https://user-images.githubusercontent.com/38330843/121285936-23c5e000-c8ad-11eb-84e4-3c130148210e.png)

_Difference observed when comparing QR code registration [staging site](https://register.covid-hcportal.cdssandbox.xyz/en/) and [Figma](https://www.figma.com/file/0CvVmmVb0EhnCmChzel70P/QR-Code-Registration-Website?node-id=3614%3A19354)_

**Comment by anikbrazeau** [comment]
@ioanacontu @YedidaZalik is an exit something to consider here?

**Comment by ioanacontu** [comment]
I need to check if these are 2 different pages or 2 different iterations of the same page... I'll get back to you! 
<img width="450" alt="Screen Shot 2021-06-14 at 11 04 11" src="https://user-images.githubusercontent.com/56094538/121914760-90533b80-cd00-11eb-8d4b-8d21d7ade8bf.png">

**Comment by ioanacontu** [comment]
Okay, so the "Invalid/Expired" screen is an older iteration of the "The link has expired" screen, which offers users a way to exit/try again. We need to update staging to this latest iteration: 
<img width="1443" alt="Screen Shot 2021-06-14 at 11 29 39" src="https://user-images.githubusercontent.com/56094538/121918407-01e0b900-cd04-11eb-82f0-cebdb2310256.png">
