### ISSUE TITLE
Super Users created through CLI are assigned to 'Ontario' by default

### ISSUE THREAD

**Issue by bryan-robitaille** [cds-snc/covid-alert-portal#60]
The default association of a Super User to the province of 'Ontario' can cause issues down the line as any user invited by a CLI created Super User with also automatically be associated with the province of 'Ontario'.

Discussion needed on how we want to address.

This issue stems from a conversation on PR #57

**Comment by pcraig3** [comment]
It's a good point.

Right now, the workarounds are:

- we can use the admin interface to manually create users
- and we can also decide who the invites come from when we send them through the admin interface
- as superusers we can change the 'province' for an account

Doesn't solve the issue but there are ways around it, if we're in a pinch.

**Comment by sboisvert** [comment]
I think for consistency sake we might want to keep issues like this in Trello so we can prioritize them with the rest of the work.
