### ISSUE TITLE
Changes to https://register.covid-hcportal.cdssandbox.xyz/en/terms

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#602]
(1) **Please replace** 

By using this website, you agree that you’re a person who’s responsible for making a poster for a place or event.
**With**
By using this website, you confirm that:  
* You’re authorized to give information so that the place or event can make posters.
* You’ve received consent to share personal information that you need to make the posters.

(2) **Please replace**
You also agree that you’ll:
**With**
You also agree to:

(3) 	**Please replace these bullets **
• If needed, update name, address or contact information by using this website to make a new poster. This changes the QR code for the place or event.
* Destroy any posters you do not need anymore or that display a previous QR code.
* Only display posters within the area that belongs to the address of the place or event.
* Display the correct poster for the address.
* Keep posters in good condition and replace damaged posters.

**With these bullets**

 •	Only display posters within the area that belongs to the address of the place or event.
 •	Display the correct poster for the address.
 •	Keep posters in good condition and replace damaged posters.
 •	If needed, use this website to update name, address or contact information . This changes the QR code for the place or event.
 •	Destroy any posters you do not need anymore or that display a previous QR code.

 (4) **Please delete**
The Government of Canada is not responsible for problems caused by damaged or altered posters. This includes altered or fake QR codes that link to apps or websites other than COVID Alert.

@EliseKa can you please also give these changes for the French?

**Comment by EliseKa** [comment]
For the French,

**(1) Replace**
En utilisant le site Web, vous acceptez d’être la personne responsable de créer une affiche pour un lieu ou un événement.

**with**
En utilisant le site Web, vous confirmez que :
- vous avez la permission de fournir des renseignements permettant de créer des affiches pour un lieu ou un événement. 
- vous avez obtenu le consentement nécessaire pour fournir les renseignements personnels requis pour créer des affiches.

**(2) Delete the following sentences:**
Le gouvernement du Canada n’est pas responsable des problèmes causés par des affiches abîmées ou modifiées. Il n’est pas responsable des codes QR modifiés ou contrefaits qui dirigent l’utilisateur vers des applications ou des sites Web autres que ceux d’Alerte COVID.


I took care of the bullet edits in PR #599

**Comment by sylviamclaughlin** [comment]
Merged and fix is in stage.
