### ISSUE TITLE
Add steps to date time selection flow

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#603]
Please add steps to date and time selection flow
Details are in this card https://trello.com/c/EZJ8oqzB/832-optimize-the-selection-in-alerting-tool

After they've added a time range, underneath the time range please put
For English:
Enter separate dates for exposures that extend past midnight.
For French:
Si l’exposition se poursuit après minuit, ajoutez une nouvelle date.

Merci!

**Comment by sylviamclaughlin** [comment]
Fixed merged and on stage.
