### ISSUE TITLE
Please change English heading for first screen of OTK flow

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#604]
https://staging.covid-hcportal.cdssandbox.xyz/en/start/  
Please change English heading to

**Now you can give one-time keys**

**Comment by sylviamclaughlin** [comment]
@YedidaZalik - I think there might be some discrepancies with another ticket. Should this be "Now you can give one-time keys" or "You are logged in to give one-time keys". Thank you so much for the clarification!

**Comment by YedidaZalik** [comment]
@sylviamclaughlin my understanding is that there will be 2 different versions of this flow:

-  Users who are authorized to give one-time-keys **and** send QR alerts will log in to this screen: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=8334%3A62464
If on that screen they choose "Give one-time-keys", then the next screen should have the heading "Now you can give one-time keys"

But, if, they are only authorized to give one-time-keys, then they'll be taken directly to the one-time-key flow when they log in. In that situation, the heading should be "You're logged in to give one-time keys".

Thanks!

**Comment by sylviamclaughlin** [comment]
@YedidaZalik - Thank you so much for the explanation! This makes it clearer.

**Comment by sylviamclaughlin** [comment]
This has been approved and merged to stage.
