### ISSUE TITLE
Please remove last set of digits from time

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#609]
In https://staging.covid-hcportal.cdssandbox.xyz/en/outbreaks/0650584f-4917-444e-b122-06ed0e04d422/datetime

Please  remove last set of digits from time, so format will be 00:00 instead of 00:00:00

Thank you!

**Comment by sylviamclaughlin** [comment]
This seems to have been fixed.

**Comment by sylviamclaughlin** [comment]
Closing this as it is fixed.
