### ISSUE TITLE
English copy showing instead of French

### ISSUE THREAD

**Issue by EliseKa** [cds-snc/covid-alert-portal#610]
On the French log in page to the portal, "Log in code" should be "Code de connexion".

<img width="600" alt="Capture d’écran, le 2021-06-09 à 14 27 03" src="https://user-images.githubusercontent.com/45772213/121741173-22bec980-cacc-11eb-8c01-c6372127a991.png">

**Comment by sylviamclaughlin** [comment]
Closing issue since fix is merged and on stage.
