### ISSUE TITLE
Change to confirmed screen 

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#614]
On https://staging.covid-hcportal.cdssandbox.xyz/en/outbreaks/confirmed

Please :

(1) remove italics from the address

(2) change name and address to bold text

(3) change the buttons to "Send another alert" and "Check alert history"

Thank you!

**Comment by sylviamclaughlin** [comment]
@YedidaZalik - I think there might be some overlap with another ticket. Can we confirm that the changes in this ticket still are valid? We can have a meeting if it makes it easier and thank you so much!

**Comment by YedidaZalik** [comment]
@sylviamclaughlin my apologies!

I made duplicate tickets for the same issue.

They're both the same, just explained differently, so please use whichever one is easier!

Sorry about this!

**Comment by sylviamclaughlin** [comment]
@YedidaZalik no problem at all! Thank you for the explanation.

**Comment by sylviamclaughlin** [comment]
The other (duplicate) ticket has been completed so I am closing this one.
