### ISSUE TITLE
Changes to registration site  Terms of use in English 

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#629]
On https://register.covid-hcportal.cdssandbox.xyz/en/terms

Please:
(1)  Replace the content under "Your responsibilities" with the following 

By using this website, you confirm that:  
You’re authorized to give information so that the place or event can make posters.
You’ve received consent to share personal information that you need to make the posters.

**You also agree to:**

Only make posters for places or events that you’re responsible for.
Enter accurate information when making posters.
Only display posters within the area that belongs to the address of the place or event.
Display the correct poster for the address.
Keep posters in good condition and replace damaged posters.
If needed, use this website to update name, address or contact information. This changes the QR code for the place or event.
Destroy any posters you do not need anymore or that display a previous QR code.

(2) Remove the first paragraph under the heading "Fraud or abuse", but keep the second paragraph.

Thanks!

**Comment by sylviamclaughlin** [comment]
This has been done and merged to main.
