### ISSUE TITLE
Error message update

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#651]
When you enter a log-in code after it expires, the error message says "You entered the wrong code". This message needs to be more generic, since the code could be expired or incorrect.

The 3 use cases covered by this error message are: 

- Entered code is in the wrong format.
- Entered code is in the right format but the code itself is wrong. 
- Entered code is expired. 

### Design

Change error message text to:
EN: **Something went wrong. Try again or ask for another code.**
FR: **Une erreur est survenue. Réessayez ou demandez un nouveau code.**

### Acceptance Criteria

* Update error message to: 
EN: **Something went wrong. Try again or ask for another code.**
FR: **Une erreur est survenue. Réessayez ou demandez un nouveau code.**

**Comment by sylviamclaughlin** [comment]
This has been merged and up on stage, so I am closing this ticket.
