### ISSUE TITLE
Content change for empty field requirement

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#653]
Please change  "This field is required." to:

EN | Enter the information.
FR | Entrez les renseignements demandés.

Thanks!

**Comment by sylviamclaughlin** [comment]
@YedidaZalik just to make sure - this ticket is no longer needed since we are doing issue #661 right? Ie we will be changing the date validation as is defined in 661 and not here, correct? Thank you so much!

**Comment by YedidaZalik** [comment]
@sylviamclaughlin for the date, month, year, please change according to 661.
But for any other error message in the portal that says "This field is required."  please change to 

EN | Enter the information.
FR | Entrez les renseignements demandés.

Thanks, and sorry, I should have explained it better!

**Comment by sylviamclaughlin** [comment]
@YedidaZalik - Thanks for the clarification Yedida!

**Comment by sylviamclaughlin** [comment]
@YedidaZalik, just to clarify - this is a change for both the registration and portal, right? Or just for one of them?  Thank you so much!

**Comment by YedidaZalik** [comment]
@sylviamclaughlin you raise a good question!
Would you be able to show me or send me a screenshot of an error message in the registration site?

**Comment by sylviamclaughlin** [comment]
@YedidaZalik here is a question for the registration site when you don't enter an email message. The first scrreenshot is how it is currently and the second screenshot is with the change:

<img width="1155" alt="Screen Shot 2021-07-02 at 9 05 27 AM" src="https://user-images.githubusercontent.com/85905333/124301493-c7a15500-db14-11eb-9e61-fd6b748f1584.png">

<img width="1122" alt="Screen Shot 2021-07-02 at 9 04 29 AM" src="https://user-images.githubusercontent.com/85905333/124301609-e99ad780-db14-11eb-9cdc-1d3acef38147.png">

**Comment by YedidaZalik** [comment]
Thanks @sylviamclaughlin !

Yes, the change to the second version is the way it should be on both sites:

"Correct these errors:
1. Enter the information."

**Comment by sylviamclaughlin** [comment]
@YedidaZalik - thanks for the clarification! The PR should be up today.

**Comment by sylviamclaughlin** [comment]
Pull Request has been submitted for this issue (https://github.com/cds-snc/covid-alert-portal/pull/676)

**Comment by sylviamclaughlin** [comment]
This has been merged and can be closed.
