### ISSUE TITLE
Add non-breaking space before colon (:) in Terms of Use French subheading

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#657]
@YedidaZalik

In terms of use of registration... `En utilisant le site Web, vous confirmez que:`

Currently:

<img width="853" alt="Screen Shot 2021-06-28 at 2 56 09 PM" src="https://user-images.githubusercontent.com/38330843/123696811-2cfdf900-d82a-11eb-88fa-a2a91d46b359.png">

Should be:

 `En utilisant le site Web, vous confirmez que :`

**Comment by YedidaZalik** [comment]
@dsamojlenko @sylviamclaughlin 
Please see the change above from @anikbrazeau on the QR code registration site

**Comment by sylviamclaughlin** [comment]
Pull request created for this one to be reviewed (https://github.com/cds-snc/covid-alert-portal/pull/669)
