### ISSUE TITLE
Registration Terms of Use Bullets in different order in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#658]
@YedidaZalik

In registration Terms of Use, French bullets don't always correspond to English. 

<img width="853" alt="Screen Shot 2021-06-28 at 4 01 15 PM" src="https://user-images.githubusercontent.com/38330843/123697921-7bf85e00-d82b-11eb-9b1c-ef06c1fffce2.png">

---

Review and correct with the following:

**Third bullet**
- **EN:** `Only display posters within the area that belongs to the address of the place or event.`
- **FR:** `Placer des affiches uniquement sur le terrain correspondant à l’adresse de votre lieu ou événement.`

**Fourth bullet**
- **EN:** `Display the correct poster for the address.`
- **FR:** `Placer la bonne affiche pour l’adresse en question.`

**Fifth bullet**
- **EN:** `Keep posters in good condition and replace damaged posters.`
- **FR:** `Maintenir les affiches en bonne condition et remplacer celles qui sont abîmées.`

**Sixth bullet**
- **EN:** `If needed, use this website to update name, address or contact information. This changes the QR code for the place or event.`
- **FR:** `Mettre à jour le nom, l’adresse ou les coordonnées dans le site Web si ces renseignements changent, afin de créer une nouvelle affiche. Un nouveau code QR sera créé pour le lieu ou l’événement en question.`

**Seventh bullet**
- **EN:** `Destroy any posters you do not need anymore or that display a previous QR code.`
- **FR:** `Détruire toute affiche dont vous n’avez plus besoin ou toute affiche ayant un ancien code QR.`

**Comment by YedidaZalik** [comment]
@dsamojlenko @sylviamclaughlin 
Please see above from @anikbrazeau for QR code registration site terms of use
Thank you!

**Comment by sylviamclaughlin** [comment]
Pull request created to be reviewed (https://github.com/cds-snc/covid-alert-portal/pull/669)
