### ISSUE TITLE
Change "Do not add" to "Cancel" - [Date/Time selection in alerting feature]

### ISSUE THREAD

**Issue by brianhendrick1** [cds-snc/covid-alert-portal#663]
@sylviamclaughlin 

HC has requested we change "Do not add" button to "Cancel"
![Date and time select_ Adding new date time - EN](https://user-images.githubusercontent.com/51927442/123822358-36d73900-d8ca-11eb-9205-214ecc0b52f7.png)

For french it will be "Annuler"

**Comment by sylviamclaughlin** [comment]
Merge request has been created https://github.com/cds-snc/covid-alert-portal/pull/664

**Comment by sylviamclaughlin** [comment]
This has been approved and merged to stage.
