### ISSUE TITLE
Changes to "Sending alerts" screen in English and French

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#694]
(1) Please make the changes shown in pink in figma

https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=7627%3A49396

(2) On that screen, in both languages, please also remove the following line at the end of the page:

"Health authorities continue to manually contact visitors who do not scan QR codes."

(3) Please also make the pink changes in the French sidebar menu, as well as in corresponding screens for the “About the portal / Support” row.

Please tag @EliseKa and myself to review.

Merci!

**Comment by sylviamclaughlin** [comment]
This is done and up for review - https://github.com/cds-snc/covid-alert-portal/pull/697

**Comment by sylviamclaughlin** [comment]
@YedidaZalik @EliseKa 
This change is now on stage.

**Comment by EliseKa** [comment]
Thanks @sylviamclaughlin! These changes look good, the only thing is that the apostrophes in these edits are straight whereas we've been using curly (typographic) apostrophes elsewhere. But this is minor, it probably could go into the backlog.

**Comment by sylviamclaughlin** [comment]
@EliseKa . Thanks for noticing this Elise. I will change this today.

**Comment by sylviamclaughlin** [comment]
This has been done and merged.
