### ISSUE TITLE
403 screen for geoblocking

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#695]
Please create the English and French screens as shown in figma:

English. https://www.figma.com/file/0CvVmmVb0EhnCmChzel70P/QR-Code-Registration-Website?node-id=4511%3A25651

French https://www.figma.com/file/0CvVmmVb0EhnCmChzel70P/QR-Code-Registration-Website?node-id=4554%3A25816

Merci!

**Comment by sylviamclaughlin** [comment]
@YedidaZalik - what is the email address that I should put for the support email? Right now it is listed as support@email.ca. Thank you so much!

**Comment by YedidaZalik** [comment]
That's a good question - I'm not sure.
@brianhendrick1 are you able to tell us?
