### ISSUE TITLE
Date and time selection error message in English and French

### ISSUE THREAD

**Issue by YedidaZalik** [cds-snc/covid-alert-portal#696]
Please create the error messages.

English:

Correct these errors:
That exposure is in the future.
Enter an exposure that has passed.

French:

Corrigez les erreurs suivantes :
La date choisie se trouve dans le futur.
Entrez la date d’une exposition passée.

Thanks!

**Comment by YedidaZalik** [comment]
After discussion, we will change this to:

EN| Correct these errors:
Something’s wrong with this date. 
Enter an exposure that has already happened.


FR | Corrigez les erreurs suivantes :
Il y a un problème avec cette date.
Entrez la date d’une exposition qui a déjà eu lieu.

**Comment by sylviamclaughlin** [comment]
This has been done and merged in by Dorian.
