### ISSUE TITLE
French title / input label / hint text on "Change your password" page 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#701]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/reset/ZmQxNThhZWItMDU1Yi00MGE3LTkyNDItZmJiMjdmZjQyYjJi/set-password/

Not the same as Figma screens: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A50020

---

### French title heading

**In Figma:** 

FR: "Modifiez votre mot de passe"

**In staging:**

FR: "Modifier votre mot de pass"

### Input label

**In Figma:** 

EN: "New password"
FR: "Nouveau mot de passe"

EN: "Enter new password again" 
FR: "Confirmation du nouveau mot de passe"

**In staging:** 

EN: "New password"
FR: "Modifier votre mot de passe"

EN: "Enter your password again" 
FR: "Saisissez de nouveau votre mot de passe"

### Hint text

**In Figma:** 

EN: "Your password must be at least 12 characters and hard to guess."
FR: "Votre mot de passe doit avoir au moins 12 caractères." <--- should this match English more closely?

**In staging:** 

EN: "Choose a password that is hard to guess, with at least 12 characters including 1 letter. The password cannot include your name, email or words related to Covid or the portal."
FR: "Choisissez un mot de passe difficile à deviner et comprenant au moins 12 caractères, dont au moins une lettre. Le mot de passe ne peut pas comprendre votre nom, votre courriel ou des mots faisant référence à la COVID ou au portail."

This hint text is also similarly different in the change your password page within the "Manage your account" section: https://staging.covid-hcportal.cdssandbox.xyz/en/profiles/fd158aeb-055b-40a7-9242-fbb27ff42b2b/edit/password

---

<img width="928" alt="Screen Shot 2021-07-26 at 1 34 24 PM" src="https://user-images.githubusercontent.com/38330843/127033350-5f4f80da-466f-481e-bad5-1f12fb867232.png">

![Screen Shot 2021-07-26 at 1 34 17 PM](https://user-images.githubusercontent.com/38330843/127033369-d1cbddb0-ad69-48a8-8b6f-c09a57e6ddec.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
