### ISSUE TITLE
About the portal > COVID Alert (French link text)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#702]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/about/

Not the same as Figma screens: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=8362%3A149

---

In Figma:
FR: "application canadienne de notification d'exposition Alerte COVID."

In staging:
FR: "application gratuite de notification d’exposition du Canada, Alerte COVID."

---
<img width="974" alt="Screen Shot 2021-07-26 at 1 49 43 PM" src="https://user-images.githubusercontent.com/38330843/127035249-7145642a-9d74-4c54-8f1f-1b785f7b529b.png">

<img width="1169" alt="Screen Shot 2021-07-26 at 1 50 07 PM" src="https://user-images.githubusercontent.com/38330843/127035267-9d732fc5-0b7d-4cf3-b983-91f9162f2810.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
