### ISSUE TITLE
About the portal > Logging in (French Subheading)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#703]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/about/create-an-account

Not the same as Figma screens: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=8362%3A440

In Figma:
FR: "Vous n'avez pas de téléphone mobile?"

In staging:
FR: "Pas de téléphone mobile?"

___

![Screen Shot 2021-07-26 at 2 11 34 PM](https://user-images.githubusercontent.com/38330843/127037816-3166da47-2a10-45ae-afdf-32de21558215.png)

<img width="748" alt="Screen Shot 2021-07-26 at 2 04 56 PM" src="https://user-images.githubusercontent.com/38330843/127037818-f749dd7e-1447-4927-8dbe-8c68567d43c4.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
