### ISSUE TITLE
About the portal > Giving keys (Missing button)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#704]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/about/give-a-key

Not the same as Figma screens: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=8362%3A1271

In Figma:
Button with "Text key to person" / "Texter la clé au patient"

In staging:
No button

---
![Screen Shot 2021-07-26 at 2 37 13 PM](https://user-images.githubusercontent.com/38330843/127041636-e382293c-7fa5-4b56-9df3-a7a3df8b2c49.png)

<img width="1281" alt="Screen Shot 2021-07-26 at 2 37 06 PM" src="https://user-images.githubusercontent.com/38330843/127041638-f4bf89b5-678a-496b-9b1e-0ddaaab3fee0.png">

**Comment by EliseKa** [comment]
Closing - this feature is not used by any province
