### ISSUE TITLE
About the portal > Helping people enter keys (French instruction button text)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#705]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/about/help-patient-enter-key

Not the same as Figma screens: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=8362%3A1224

---

### French instruction button text

In Figma:
# 2 in the list of instructions says `« Entrer une clé à usage unique »`

In staging:
# 2 in the list of instructions says `« Entrer une clé »`

---

<img width="883" alt="Screen Shot 2021-07-26 at 2 46 30 PM" src="https://user-images.githubusercontent.com/38330843/127042779-492643b9-a34e-4a97-8c62-0dd719e55406.png">

![Screen Shot 2021-07-26 at 2 46 25 PM](https://user-images.githubusercontent.com/38330843/127042781-bc7e5e26-37c2-44b1-92dd-5c18c9de1d2d.png)

**Comment by sylviamclaughlin** [comment]
@anikbrazeau 
This involves a new updated image with the correct french translation. How should I go about obtaining a new image or who should I contact? Also, is this something that we still want to pursue given that an image needs to be updated? Thank you so much!

**Comment by anikbrazeau** [comment]
CC @EliseKa

**Comment by EliseKa** [comment]
@sylviamclaughlin
The image doesn't need to be updated, only the copy before the screenshot so it says the same thing as what is in the screenshot.

**Comment by sylviamclaughlin** [comment]
@EliseKa 
Thank you for the clarification.

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
