### ISSUE TITLE
Terms of use bolding in English

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#706]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/terms/

Not the same as Figma screens: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7814%3A2

---

In Figma:
`and` is bolded

In staging:
`and` is not bolded

---

![Screen Shot 2021-07-27 at 7 30 31 AM](https://user-images.githubusercontent.com/38330843/127146806-88c6b055-71bd-44b9-85b6-5d2b42143a57.png)

<img width="868" alt="Screen Shot 2021-07-27 at 7 32 22 AM" src="https://user-images.githubusercontent.com/38330843/127146809-efde8038-00ae-4f9f-84cb-9db082463a11.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
