### ISSUE TITLE
Terms of use shows up in English on French page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#707]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/terms/

Figma FR content: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=10043%3A84074

Update translations

---

![Screen Shot 2021-07-27 at 7 36 32 AM](https://user-images.githubusercontent.com/38330843/127147449-5dd9707b-f26b-497c-a1ee-da3b6f566d91.png)

<img width="678" alt="Screen Shot 2021-07-27 at 7 38 01 AM" src="https://user-images.githubusercontent.com/38330843/127147487-18f8208b-d577-45ad-97f8-910014f136c6.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
