### ISSUE TITLE
Link to Privacy Commissioner site for French Privacy Statement

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#708]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/privacy/

Figma FR content: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A54328

Add link for `Privacy Commissioner of Canada` in French

`commisaire à la protection de la vie privée du Canada`
https://www.priv.gc.ca/fr/pour-les-individus/

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
