### ISSUE TITLE
Contact us > Unbold (optional)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#709]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/contact/

Figma FR content: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A50401

---

Unbold `(optional)`/`(facultatif)`  on Contact us form in EN / FR

---

<img width="721" alt="Screen Shot 2021-07-27 at 7 52 40 AM" src="https://user-images.githubusercontent.com/38330843/127149314-d9f176e0-05e8-43fc-9639-f8c5ccda428a.png">

**Comment by sylviamclaughlin** [comment]
Even though this seems like an easy fix, it is not. The way the form is constructed, we can't isolate part of the label to be non bold unless we completely redesign the form. As a result, I am closing this issue.
