### ISSUE TITLE
2FA Log in codes copy

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#710]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/login-2fa/?next=/en/start/

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A53277

---

Update paragraph text in EN and FR
<img width="591" alt="Screen Shot 2021-07-27 at 8 15 22 AM" src="https://user-images.githubusercontent.com/38330843/127152149-50aed956-9d06-45ca-9b17-c62d036fc131.png">

<img width="697" alt="Screen Shot 2021-07-27 at 8 16 58 AM" src="https://user-images.githubusercontent.com/38330843/127152157-e33a9a7c-5537-4a8d-ba20-6a04f1e4529b.png">

**Comment by EliseKa** [comment]
closing - The copy seems alright, maybe you got a different page with different content because you generated offline codes earlier. In that case, the content says you can either enter the code sent by text or one of the offline codes.
