### ISSUE TITLE
Button on 'No log in code?' page in French shows up in English

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#711]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/backup-codes-help

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A53319

---
Replace "Get code from admin" with "Demander un code"
---
![Screen Shot 2021-07-27 at 8 20 24 AM](https://user-images.githubusercontent.com/38330843/127152642-075f9c4d-41b1-46d4-8d50-ae6ac0cce7a1.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
