### ISSUE TITLE
Portal start page (key singular vs. keys plural)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#712]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/start/
`Give a key`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=8334%3A62464
`Give keys`

--- 

![Screen Shot 2021-07-27 at 8 29 14 AM](https://user-images.githubusercontent.com/38330843/127259949-ec1a75fa-ddfa-4ca1-8e16-bd8dbb366d1e.png)

<img width="923" alt="Screen Shot 2021-07-27 at 8 29 09 AM" src="https://user-images.githubusercontent.com/38330843/127259950-0ec6fb18-e155-4635-a1c3-6ec65d12ca5b.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
