### ISSUE TITLE
One-time-key start page French Heading

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#713]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/otk-start/
`Clés à usage unique`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=9004%3A881
`Vous pouvez maintenant donner des clés`

---

![Screen Shot 2021-07-27 at 11 48 06 PM](https://user-images.githubusercontent.com/38330843/127260509-3f2ccd2e-58fb-4598-9795-08dc8e86b780.png)

<img width="419" alt="Screen Shot 2021-07-27 at 11 47 55 PM" src="https://user-images.githubusercontent.com/38330843/127260510-0d7c4113-7a8c-4649-b9de-248042902853.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
