### ISSUE TITLE
Generated key screen - French heading

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#714]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/key/
`Donnez la clé suivante`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A54077
`Donnez la clé suivante au patient`

**Comment by EliseKa** [comment]
closing - Figma was not up to date.
