### ISSUE TITLE
Non-breaking spaces in French before colons ( :) and around text in quotes (« text »)

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#715]
Use non-breaking spaces between `«  »` and the words they surround

---

![Screen Shot 2021-07-26 at 2 48 01 PM](https://user-images.githubusercontent.com/38330843/127042777-89d77a68-3d95-4d13-9a8b-74d65be05f6d.png)

![Screen Shot 2021-07-28 at 12 01 16 AM](https://user-images.githubusercontent.com/38330843/127261520-4e28721c-4b16-486e-98ae-1d2886db21c6.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
