### ISSUE TITLE
Button for "Change your name" in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#716]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/profiles/fd158aeb-055b-40a7-9242-fbb27ff42b2b/edit/name
Button copy = `Modifier`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A50362
Button copy = `Mettre à jour`

---

![Screen Shot 2021-07-28 at 12 04 53 AM](https://user-images.githubusercontent.com/38330843/127261956-584691a3-550b-4265-957a-b37a026fe6c7.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
