### ISSUE TITLE
EN hint text on "Change your mobile phone number" page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#717]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/profiles/fd158aeb-055b-40a7-9242-fbb27ff42b2b/edit/phone
Confirm phone number hint text: `Enter the phone number again`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A50385
Confirm phone number hint text: `Enter the same mobile number as above`

---
![Screen Shot 2021-07-28 at 12 08 34 AM](https://user-images.githubusercontent.com/38330843/127262221-bcb9c144-36fc-4c55-9690-447450a6773a.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
