### ISSUE TITLE
Missing "encore" in log in codes page FR

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#718]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/backup-codes

Not the same as Figma screens: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A52695
`...qui n'ont pas **encore** été utilisés...`

---

<img width="416" alt="Screen Shot 2021-07-28 at 12 14 07 AM" src="https://user-images.githubusercontent.com/38330843/127262753-adb47bc9-c634-46d1-b1f3-d8c1ff774cdb.png">

**Comment by EliseKa** [comment]
closing - low priority and copy works fine as it is. Figma updated to reflect this.
