### ISSUE TITLE
Missing "plus tard" in 'Delete account' screen in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#719]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/profiles/69e63273-85de-443f-92a6-8b1e72026f14/delete
`Vous pouvez toujours créer un nouveau compte pour cette personne.`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A50326
`Vous pouvez toujours créer un nouveau compte pour cette personne **plus tard**.`

---

<img width="407" alt="Screen Shot 2021-07-28 at 12 21 55 AM" src="https://user-images.githubusercontent.com/38330843/127263336-8b1e744c-5aff-47d7-8be5-8c520086e0ce.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
