### ISSUE TITLE
Alignment issue with links on 'Invitations' page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#720]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/invite/list/

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A50104

Resend and delete buttons are staggered, should be right aligned?

---

![Screen Shot 2021-07-28 at 12 24 27 AM](https://user-images.githubusercontent.com/38330843/127263471-b856d6e7-2444-48b9-9c18-2269b60780c3.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
