### ISSUE TITLE
Offline 2FA - French heading and paragraph text

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#721]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/signup/backup-codes

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A53550

---
**Heading**
`Vous n'avez pas de téléphone mobile?`

**Second paragraph**
`Avant toute autre chose, enregistrez ces codes dans un endroit auquel vous seul pouvez accéder. Ne les envoyez pas par courriel, ni à vous ni à aucune autre personne. Ne les enregistrez pas sur un ordinateur partagé ni sur un appareil non protégé par un mot de passe.`

<img width="620" alt="Screen Shot 2021-07-28 at 12 43 19 AM" src="https://user-images.githubusercontent.com/38330843/127265020-56150e89-1072-4969-8d61-f25087af4c2d.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
