### ISSUE TITLE
Alert history page in French

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#722]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/outbreaks/dee00fb9-2a9d-4d9d-b380-0dd2e752ebab/history?sort=start_date&order=asc

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=8461%3A63551

---

### Heading
`Historique des alertes`

### Second column label
`Date d'envoi de l'alerte`

---

![Screen Shot 2021-07-28 at 1 01 48 AM](https://user-images.githubusercontent.com/38330843/127266464-880a18b7-06ee-4b7d-8762-3a25043db0c7.png)

<img width="648" alt="Screen Shot 2021-07-28 at 1 01 44 AM" src="https://user-images.githubusercontent.com/38330843/127266466-a3c398fa-912b-4997-b72a-a04b71bd40d3.png">

**Comment by EliseKa** [comment]
fyi: I believe the heading uses the same string as the linked text in this banner, and it should not.
The Heading should be "Historique des alertes", with a capital letter, and the linked text in the banner should stay like it is.
<img width="649" alt="Capture d’écran, le 2021-07-28 à 11 18 35" src="https://user-images.githubusercontent.com/45772213/127348891-94868127-b426-4e96-8512-15aac84615f4.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
