### ISSUE TITLE
Details of exposure page -- missing row

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#723]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/outbreaks/29f1f780-29f9-4e66-8fa9-01d31ed16386/details

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A63593

---

Add "Number of devices alerted" // "Nombre d'appareils alertés" ?

**Comment by EliseKa** [comment]
closing - this was an out-of-scope feature
