### ISSUE TITLE
Alert history page - Addresses in italics and different date format

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#724]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/outbreaks/history?sort=name&order=asc

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=8866%3A175 

---

In Figma, address is not italics and date is in "12 Jan 2021" format.

![Screen Shot 2021-07-28 at 1 06 16 AM](https://user-images.githubusercontent.com/38330843/127266869-3cf18bd5-7e6c-437d-9674-3db7e789a703.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
