### ISSUE TITLE
Alignment issue with date fields on 'Choose date and time' screen

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#725]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/outbreaks/99c0f622-0382-470f-86f3-29d6aa2aa232/datetime

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7877%3A0

---

Month dropdown is a bit wonky

![Screen Shot 2021-07-28 at 1 11 41 AM](https://user-images.githubusercontent.com/38330843/127267306-3c8878ab-ff37-46ef-ab59-9794cc45b5f6.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
