### ISSUE TITLE
Choose date and time screen - difference in table name

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#726]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/outbreaks/99c0f622-0382-470f-86f3-29d6aa2aa232/datetime#time-fields
`Exposure dates`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7877%3A102
`Selected dates`

**Comment by EliseKa** [comment]
closing - this figma screen was not updated
