### ISSUE TITLE
FR button on date and time select - "Abandonner"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#727]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/outbreaks/98b6369c-18fa-42fd-b789-90bac001edd5/datetime
`Détails de l'exposition`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=9627%3A3
`Abandonner`

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
