### ISSUE TITLE
Date and time formats need to work in French 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#728]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/outbreaks/98b6369c-18fa-42fd-b789-90bac001edd5/datetime#time-fields

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=9614%3A67549

---
Date and time posted in English format in French screens

No AM / PM in French

![Screen Shot 2021-07-28 at 1 20 12 AM](https://user-images.githubusercontent.com/38330843/127267962-ef89ffd8-2276-4c2e-ba12-f270c88c00ff.png)

![Screen Shot 2021-07-28 at 1 23 27 AM](https://user-images.githubusercontent.com/38330843/127268295-93fdfff7-e0e6-4924-b12d-4b99cc1dd9cd.png)

![Screen Shot 2021-07-28 at 1 25 37 AM](https://user-images.githubusercontent.com/38330843/127268445-02a7db0d-a15c-4781-92c9-eefed769ee8b.png)

**Comment by sylviamclaughlin** [comment]
I am closing this issue since the rework for this functionality to be implemented will be quite intensive.
