### ISSUE TITLE
Change button copy on Adding new date screen

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#729]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/outbreaks/98b6369c-18fa-42fd-b789-90bac001edd5/datetime#time-fields
`Annuler`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=9542%3A67451
`Annuler l'ajout`

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
