### ISSUE TITLE
Cancel this exposure button in French should be "Abandonner"

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#730]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/outbreaks/confirm (and other pages)

Button says "Détails de l'exposition"

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A64092
"Abandonner"

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
