### ISSUE TITLE
Alignment issue with buttons on the review page

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#731]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/fr/outbreaks/confirm

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A64092

---

Buttons should be side-by-side as on other pages

![Screen Shot 2021-07-28 at 1 29 05 AM](https://user-images.githubusercontent.com/38330843/127268849-fb127318-3d1d-46ba-b1ad-51f998a04377.png)

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
