### ISSUE TITLE
Button copy on final confirmation page after sending alerts

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/covid-alert-portal#732]
Discrepancy on https://staging.covid-hcportal.cdssandbox.xyz/en/outbreaks/confirmed

Primary button: `Notify of another public exposure`
Secondary button: `Search notification history`

Figma: https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification-Health-Portal?node-id=7627%3A64188

Primary button: `Send another alert`
Secondary button: `Check alert history`

---

<img width="446" alt="Screen Shot 2021-07-28 at 1 35 58 AM" src="https://user-images.githubusercontent.com/38330843/127269250-cb41c007-6688-40f2-8c4e-525a1efc1d40.png">

**Comment by sylviamclaughlin** [comment]
Pull Request for this issue has been created - https://github.com/cds-snc/covid-alert-portal/pull/733

**Comment by sylviamclaughlin** [comment]
Merged in stage and production.
